# Generated by Django 4.2.13 on 2024-05-12 02:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0019_coursetask_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="photo",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
