# Generated by Django 4.2.13 on 2024-05-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0020_course_created_time_course_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="teachers",
            field=models.CharField(default="任课教师1;任课教师2", max_length=200),
        ),
    ]
