# Generated by Django 4.2.13 on 2024-05-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0022_alter_course_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="photo",
            field=models.CharField(
                default="https://cdn.classpoint.io/wp-content/uploads/What-is-Personalized-Learning-2048x1280.webp",
                max_length=2000,
            ),
        ),
    ]
